### ISSUE TITLE
Cannot expose app at different path then `/`

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tf_cockpit#17]
I want to be able to build the app so it can be exposed on a web server at a different URL path than `/`

I found https://github.com/threefoldtech/tf_cockpit/blob/6137ca8af416b1db986dda9b423ba19925f2c54d/src/router.js#L9
So I tried to build the application with `BASE_URL=/cockpit yarn build`
and then server the content of the dist folder in my web server at `/cockpit` but all the files (js,css,...) returns a 404.

**Comment by DylanVerstraete** [comment]
With https://github.com/threefoldtech/tf_cockpit/commit/2d679b9e669f047e6f360b9e9a0e0ec54b9b66c8

When you build the app, you go to the `dist` folder. Then you move `css`, `js`, `img`, `fonts` folders to a folder called `cockpit` in `dist`. When you deploy the app the base url should be `/cockpit/`

Edit: This is not the most wanted solution, you can provide an [assetsDir](https://cli.vuejs.org/config/#assetsdir) property to the `vue.config.js` file. When you set this to `cockpit`, then static files are outputted in this directory. This does solve the moving of directory problem but raises another problem. All the static file url's in the `index.html` are now rewritten to `/cockpit/cockpit/...somefile`, which is not what we want. I have looked in the webpack loaders but I can't seem to figure it out. @coeneivan maybe you know how to solve this? 

@zaibon With this commit you should alteast have to ability to deploy the app with `/cockpit/` url.

**Comment by coeneivan** [comment]
This can be fixed by adding a `vue.config.js` file with following content.
```
module.exports = {
  publicPath: process.env.NODE_ENV === 'production'
    ? '/cockpit/'
    : '/'
}
```
