### ISSUE TITLE
As a farmer import data

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/tf_cockpit#24]
As a farmer you should be able to import farm data

**Assumptions**
- Farmer will be created in the central Cockpit 3bot instantion
- Decentralization is out of scope for now
- In the Phonebook or Cockpit, a farmer is not an entity. A user can just own farms. 
- You can click the farmer icon wether you are logged in or not
**More info**

After clicking the farmer icon in the UI
![image](https://user-images.githubusercontent.com/1687505/67004836-77d0ef00-f0e1-11e9-8465-3ce81b37aff4.png)

The user will be redirected to the farming page. If the user is not logged in, the user will be redirected first to login. If the user does not have a farm yet, it is important that we can get legacy data from his old account.

After that the user will be able to login with his IYO account
![image](https://user-images.githubusercontent.com/1687505/67004545-d6499d80-f0e0-11e9-8031-7c6cb753c485.png)

This can all be done on the frontend, after which all the data can be pulled from legacy systems. The data can be put using the same API call that is used to create a farm:

/farms/put
```json
{
"name": "my farm",
"organizationId" : "myorgid",
wallet_addresses : [ "myWalletaddress" ],
"location" : { "lat" : 51.180303, "long" : 3.209025},
"email", "my@tf.org"
"resource_prices" : {
    "cru" : 1.2,
    "mru" : 1.2,
    "hru" : 1.2,
    "sru" : 1.2,
    "nru" : 1.2
    }
}
```

Flow in chart:

![image](https://user-images.githubusercontent.com/1687505/67005291-94b9f200-f0e2-11e9-8f9d-9127a3f37d4d.png)

**DOD**
- UI is linked to actors
- Import from IYO is tested and done
- Import is re-asked as long as user has no farms

**TODO**
resource_prices

**Comment by jdelrue** [comment]
@zaibon @gmachtel @MathiasDeWeerdt Review? Additions?

**Comment by zaibon** [comment]
That looks about right.
Here is the URL of the API of the old directory where you can get the defailt of a legacy farm:
`https://capacity.threefoldtoken.com/api/farmers/{iyo_organization}`

**Comment by jdelrue** [comment]
Double!
