### ISSUE TITLE
As a user, see token page

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/tf_cockpit#30]
**Status**

Token page is already implemented UI side, however actors still load dummy code.

![image](https://user-images.githubusercontent.com/1687505/67384401-6714f300-f591-11e9-8c34-7c1b01e9bcb7.png)

**Data**
- News: fetched from [here](https://github.com/threefoldfoundation/info_tokens/tree/development/docs/news) 
- Token ???

**Comment by robvanmieghem** [comment]
Total number of tokens: https://github.com/threefoldfoundation/tfchain/issues/378
