### ISSUE TITLE
Implement Gedis actor for each part of the cockpit

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/tf_cockpit#7]
This issue tracks the progress for each of the actor needed by the cockpits:

- [x] : capacity directory
    - [x] register new farm
    - [x] update farm detail
    - [x] get farm detail
    - [x] list farms
    - [x] list all nodes. Possibility to filter by resource units, location, farm
    - [x] get node detail
    - [x] update node total capacity
    - [x] update node reserved capacity
    - [x] update node used capacity
- [ ] : token exchange
    - [ ] To be defined 
- [ ] : workload reservation
    - [ ] reserve container
    - [ ] reserve volume
    - [ ] reserve 0-db
    - [ ] reserve network

Current location of the gedis actor is: https://github.com/threefoldtech/jumpscaleX_threebot/tree/master/ThreeBotPackages/threefold/directory

Refer to https://github.com/threefoldtech/tf_cockpit/issues/5#issuecomment-522575303
for the detail about what schema to use.

**Comment by zaibon** [comment]
Started working on the node/farm actors. But nothing has been really tested, threebot framework broke in the middle of the day, so I'm now blocked.

**Comment by zaibon** [comment]
actors for nodes and farms have been merged in: https://github.com/threefoldtech/jumpscaleX_threebot/pull/3

**Comment by despiegk** [comment]
new story being created
